import type { Metadata } from 'next'
import { Providers } from '../providers'
import AdminSidebar from '@/components/sidebars/AdminSidebar';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
    title: 'Econo Market',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <Providers>
                <body className={`flex min-h-screen`}>
                    <AdminSidebar/>
                    <div className='flex grow w-full px-4 py-4 justify-center'>
                        {children}
                    </div>
                </body>
            </Providers>
        </html>
    )
}
